/*
 *  The MIT License
 * 
 *  Copyright 2011 Edwin Bratini <edwin.bratini@gmail.com>.
 * 
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 * 
 *  The above copyright notice and this permission notice shall be included in
 *  all copies or substantial portions of the Software.
 * 
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *  THE SOFTWARE.
 */

/*
 * JalgorGM.java
 *
 * Created on May 29, 2011, 6:08:14 PM
 */

package org.uasd.jalgor.ui;

/**
 *
 * @author Edwin Bratini <edwin.bratini@gmail.com>
 */
public class JalgorGM extends javax.swing.JFrame {

    /** Creates new form JalgorGM */
    public JalgorGM() {
        LookAndFeelSelector.setLookAndFeel(LookAndFeelSelector.LAF.WINDOWS);
        setLocationByPlatform(true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrLaf = new javax.swing.ButtonGroup();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        pnlBotonesAccion = new javax.swing.JPanel();
        btnCompilar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaSalidaJalgor = new javax.swing.JTextArea();
        lblSalidaJalgor = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnlSourceFile = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaSourceFile = new javax.swing.JTextArea();
        txtSourceFilePath = new javax.swing.JTextField();
        btnBuscarSrcFilePath = new javax.swing.JButton();
        pnlOutFile = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaOutFile = new javax.swing.JTextArea();
        txtOutFilePath = new javax.swing.JTextField();
        btnBuscarOutFilePath = new javax.swing.JButton();
        mnuMenuBar = new javax.swing.JMenuBar();
        mnuJalgor = new javax.swing.JMenu();
        mnuCompilar = new javax.swing.JMenuItem();
        mnuLimpiarCampos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        mnuLaf = new javax.swing.JMenu();
        rdbWindowsLaf = new javax.swing.JRadioButtonMenuItem();
        rdbNimbusLaf = new javax.swing.JRadioButtonMenuItem();
        rdbMetalLaf = new javax.swing.JRadioButtonMenuItem();
        mnuInfo = new javax.swing.JMenu();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jalgor: Algorithm Interpreter");
        setResizable(false);

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 837, Short.MAX_VALUE)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel))
                .addGap(3, 3, 3))
        );

        pnlBotonesAccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCompilar.setText("Compilar");

        btnLimpiar.setText("Limpiar");

        javax.swing.GroupLayout pnlBotonesAccionLayout = new javax.swing.GroupLayout(pnlBotonesAccion);
        pnlBotonesAccion.setLayout(pnlBotonesAccionLayout);
        pnlBotonesAccionLayout.setHorizontalGroup(
            pnlBotonesAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesAccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCompilar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotonesAccionLayout.setVerticalGroup(
            pnlBotonesAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesAccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCompilar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        jtaSalidaJalgor.setColumns(20);
        jtaSalidaJalgor.setEditable(false);
        jtaSalidaJalgor.setRows(5);
        jScrollPane3.setViewportView(jtaSalidaJalgor);

        lblSalidaJalgor.setText("Salida");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jSplitPane1.setResizeWeight(1.0);

        pnlSourceFile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlSourceFile.setMinimumSize(new java.awt.Dimension(10, 10));
        pnlSourceFile.setPreferredSize(new java.awt.Dimension(347, 348));

        jtaSourceFile.setColumns(20);
        jtaSourceFile.setRows(5);
        jScrollPane1.setViewportView(jtaSourceFile);

        txtSourceFilePath.setText("path archivo fuente");

        btnBuscarSrcFilePath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/searchglass_vflip.gif"))); // NOI18N
        btnBuscarSrcFilePath.setBorder(null);
        btnBuscarSrcFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSrcFilePathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSourceFileLayout = new javax.swing.GroupLayout(pnlSourceFile);
        pnlSourceFile.setLayout(pnlSourceFileLayout);
        pnlSourceFileLayout.setHorizontalGroup(
            pnlSourceFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSourceFileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSourceFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSourceFileLayout.createSequentialGroup()
                        .addComponent(txtSourceFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarSrcFilePath)))
                .addContainerGap())
        );
        pnlSourceFileLayout.setVerticalGroup(
            pnlSourceFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSourceFileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSourceFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarSrcFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSourceFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(pnlSourceFile);

        pnlOutFile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlOutFile.setMinimumSize(new java.awt.Dimension(10, 10));
        pnlOutFile.setPreferredSize(new java.awt.Dimension(372, 350));

        jtaOutFile.setColumns(20);
        jtaOutFile.setRows(5);
        jScrollPane2.setViewportView(jtaOutFile);

        txtOutFilePath.setText("path archivo salida");

        btnBuscarOutFilePath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/searchglass_vflip.gif"))); // NOI18N
        btnBuscarOutFilePath.setBorder(null);
        btnBuscarOutFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarOutFilePathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOutFileLayout = new javax.swing.GroupLayout(pnlOutFile);
        pnlOutFile.setLayout(pnlOutFileLayout);
        pnlOutFileLayout.setHorizontalGroup(
            pnlOutFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOutFileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOutFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOutFileLayout.createSequentialGroup()
                        .addComponent(txtOutFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarOutFilePath)))
                .addContainerGap())
        );
        pnlOutFileLayout.setVerticalGroup(
            pnlOutFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOutFileLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlOutFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarOutFilePath)
                    .addComponent(txtOutFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(pnlOutFile);

        mnuJalgor.setText("Jalgor");
        mnuJalgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuJalgorActionPerformed(evt);
            }
        });

        mnuCompilar.setText("Compilar");
        mnuJalgor.add(mnuCompilar);

        mnuLimpiarCampos.setText("Limpiar Campos");
        mnuJalgor.add(mnuLimpiarCampos);
        mnuJalgor.add(jSeparator1);

        mnuSalir.setText("Salir");
        mnuJalgor.add(mnuSalir);

        mnuMenuBar.add(mnuJalgor);

        mnuLaf.setText("L&F");

        bgrLaf.add(rdbWindowsLaf);
        rdbWindowsLaf.setSelected(true);
        rdbWindowsLaf.setText("Windows");
        mnuLaf.add(rdbWindowsLaf);

        bgrLaf.add(rdbNimbusLaf);
        rdbNimbusLaf.setText("Nimbus");
        mnuLaf.add(rdbNimbusLaf);

        bgrLaf.add(rdbMetalLaf);
        rdbMetalLaf.setText("Metal");
        mnuLaf.add(rdbMetalLaf);

        mnuMenuBar.add(mnuLaf);

        mnuInfo.setText("?");

        mnuAbout.setText("About");
        mnuInfo.add(mnuAbout);

        mnuMenuBar.add(mnuInfo);

        setJMenuBar(mnuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSalidaJalgor)
                .addContainerGap(819, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlBotonesAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlBotonesAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addComponent(lblSalidaJalgor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarSrcFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSrcFilePathActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnBuscarSrcFilePathActionPerformed

    private void btnBuscarOutFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarOutFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarOutFilePathActionPerformed

    private void mnuJalgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuJalgorActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuJalgorActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JalgorGM().setVisible(true);
            }
        });
    }

    private void limpiar() {
    }

    private void compilar(String sourceFilePath, String outFilePath) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrLaf;
    private javax.swing.JButton btnBuscarOutFilePath;
    private javax.swing.JButton btnBuscarSrcFilePath;
    private javax.swing.JButton btnCompilar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jtaOutFile;
    private javax.swing.JTextArea jtaSalidaJalgor;
    private javax.swing.JTextArea jtaSourceFile;
    private javax.swing.JLabel lblSalidaJalgor;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenuItem mnuCompilar;
    private javax.swing.JMenu mnuInfo;
    private javax.swing.JMenu mnuJalgor;
    private javax.swing.JMenu mnuLaf;
    private javax.swing.JMenuItem mnuLimpiarCampos;
    private javax.swing.JMenuBar mnuMenuBar;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JPanel pnlBotonesAccion;
    private javax.swing.JPanel pnlOutFile;
    private javax.swing.JPanel pnlSourceFile;
    private javax.swing.JRadioButtonMenuItem rdbMetalLaf;
    private javax.swing.JRadioButtonMenuItem rdbNimbusLaf;
    private javax.swing.JRadioButtonMenuItem rdbWindowsLaf;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTextField txtOutFilePath;
    private javax.swing.JTextField txtSourceFilePath;
    // End of variables declaration//GEN-END:variables

}
